spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true
    username: springstudent
    password: springstudent

  jpa:
    hibernate.ddl-auto: create
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    root: warn